apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.webapp.name }}-pvc-rook
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: {{ .Values.webapp.storage.size | default "1Gi" }}