{{- if .Values.fahrtbags.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: fahrtbags-redirect
  namespace: {{ .Release.Namespace }}
spec:
  redirectRegex:
    regex: ".*"
    replacement: "{{ .Values.fahrtbags.redirectTo }}"
    permanent: true
{{- end }}
