apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapp.name }}-flower
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}-flower
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}-flower
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/cpu-cpuid.AVX2
                operator: In
                values:
                - "true"
      containers:
      - name: {{ .Values.webapp.name }}-flower
        image: {{ .Values.webapp.container.image }}
        resources:
{{ toYaml .Values.flower.resources | indent 10 }}
        args:
          - celery
          - -A
          - nickknows.celery
          - flower
          - --port=5555
          - --url_prefix=flower
        ports:
          - containerPort: 5555