apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.webapp.name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: {{ .Values.webapp.storage.size | default "1Gi" }}