apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.webapp.name }}-pvc
  namespace: {{ .Release.Namespace }}
  annotations: {
    volume.kubernetes.io/selected-node: "gingmachine"
  }
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.webapp.storage.size | default "1Gi" }}