apiVersion: v1
kind: Service
metadata:
  name: redis-dev
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis-dev
    group: {{ .Values.webapp.group }}
spec:
  ports:
    - name: redis-dev
      port: 6379
      protocol: TCP
  selector:
    app: redis-dev