apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
    spec:
      containers:
      - name: {{ .Values.webapp.name }}
        env:
        - name: FLASK_SECRET
          value: $MY_VALUE
        image: {{ .Values.webapp.container.image }}
        imagePullPolicy: {{ .Values.webapp.container.imagePullPolicy }}
        resources:
          limits:
            memory: {{ .Values.webapp.container.memory }}
            cpu: {{ .Values.webapp.container.cpu }}
        ports:
        - containerPort: {{ .Values.webapp.container.port }}
        volumeMounts:
        - name: data-volume
          mountPath: /NickKnows/app/nickknows/nfl/data
        - name: images-volume
          mountPath: /NickKnows/app/nickknows/static/images
        resources:
          limits:
            cpu: '0'
            memory: '0'
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ .Values.webapp.name }}-pvc
      - name: images-volume
        persistentVolumeClaim:
          claimName: {{ .Values.webapp.name }}-images-pvc