apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
  annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      # Ensure backend knows it's behind HTTPS
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      # Forward protocol headers to Flask app
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
      kubernetes.io/ingress-class: nginx
      external-dns.alpha.kubernetes.io/target: "8.44.158.127"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.webapp.fqdn}}
      secretName: nickknows-tls
  rules:
  - host: {{ .Values.webapp.fqdn }}
    http:
      paths:
      - path: {{ .Values.webapp.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webapp.name }}
            port:
              number: {{ .Values.webapp.container.port }}
      - path: /flower
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webapp.name }}-flower
            port:
              number: 5555