# This workflow checksout the most recent code, builds a container image for Flask, 
# and pushes it to docker.io before updating the Helm chart and pushing the changes back to the code repository
name: Nick Knows Flask CI/CD - GHArc Scale Set

on: 
  push:
    paths:
      - app/**

jobs:
  build-image-update-helm:
    runs-on: gh-arc-nickknows-scale-set
    steps:
      - name: Check out the code repository
        uses: actions/checkout@v4
      - name: Login to Harbor
        run: |
          docker login -u ${{ secrets.HARBOR_USER }} -p ${{ secrets.HARBOR_PASS }} harbor.ging.nickknows.net
      - name: Get the current date for an image tag
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H.%M')" >> $GITHUB_OUTPUT
      - name: Build and push Nick Knows Flask image"
        run: |
          docker buildx create --use --driver=remote tcp://buildkit-buildkit-service.arc-systems:1234
          docker buildx build --push -t harbor.ging.nickknows.net/nickknows/nick-knows:${{ steps.date.outputs.date }} .
      - name: Update Helm chart with new image
        run: |
          sed -i "/nick-knows/ c\    image: harbor.ging.nickknows.net/nickknows/nick-knows:${{ steps.date.outputs.date }}" helm_knows/values.yaml
      - name: Push changes to GitHub
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git commit -a -m "Image build and push successful, updated Helm chart to use new image"
          git push